export const DOCS_LIST_REQUEST = "DOCS_LIST_REQUEST";
export const DOCS_LIST_SUCCESS = "DOCS_LIST_SUCCESS";
export const DOCS_LIST_FAIL = "DOCS_LIST_FAIL";

export const DOCS_CREATE_REQUEST = "DOCS_CREATE_REQUEST";
export const DOCS_CREATE_SUCCESS = "DOCS_CREATE_SUCCESS";
export const DOCS_CREATE_FAIL = "DOCS_CREATE_FAIL";

export const DOCS_UPDATE_REQUEST = "DOCS_UPDATE_REQUEST";
export const DOCS_UPDATE_SUCCESS = "DOCS_UPDATE_SUCCESS";
export const DOCS_UPDATE_FAIL = "DOCS_UPDATE_FAIL";

export const DOCS_DELETE_REQUEST = "DOCS_DELETE_REQUEST";
export const DOCS_DELETE_SUCCESS = "DOCS_DELETE_SUCCESS";
export const DOCS_DELETE_FAIL = "DOCS_DELETE_FAIL";